// Code generated by "stringer -type=AccessLevel"; DO NOT EDIT.

package userPackage

import "fmt"

const _AccessLevel_name = "AccessLevelUserAccessLevelContributorAccessLevelAdmin"

var _AccessLevel_index = [...]uint8{0, 15, 37, 53}

func (i AccessLevel) String() string {
	if i < 0 || i >= AccessLevel(len(_AccessLevel_index)-1) {
		return fmt.Sprintf("AccessLevel(%d)", i)
	}
	return _AccessLevel_name[_AccessLevel_index[i]:_AccessLevel_index[i+1]]
}
